
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - "/media"

notify:
  - name: "Mail"
    platform: smtp
    server: smtp.gmail.com
    port: 587
    sender: "hocongtoan987@gmail.com"
    recipient:
      - n22dccn042@student.ptithcm.edu.vn
    starttls: true
    username: hocongtoan987@gmail.com
    password: xuti imkl kqwy qxqq